import { ActivityIcon, BellIcon, BookOpenIcon, BrainIcon, CpuIcon, EyeIcon, Gamepad2Icon, GlobeIcon, HeartIcon, Music2Icon, PaletteIcon, PlayIcon, SunIcon, TargetIcon, VideoIcon } from 'lucide-react';

// ─── Scenes Data ────────────────────────────────────────────────────────────

export const DESKTOP_COMBO_PROMPTS = [
  // ── Research + Build ──
  { id: 'news-monster', label: '📰 News Monster Collage', icon: GlobeIcon, category: 'Research + Build', prompt: 'Research the latest global news headlines from today, then generate an AI image of a fuzzy cuddling anthropomorphic monster expressing how he feels about the news with a word cloud of headlines around him, and then build a highly detailed CSS recreation of a newspaper front page about today\'s top stories using the real headlines from the research.' },
  { id: 'stock-dashboard', label: '📈 Live Stock Tracker', icon: ActivityIcon, category: 'Research + Build', prompt: 'Research the top 10 trending stocks today with their prices, percentage changes, and market sentiment, then build a professional dark-mode stock trading dashboard displaying real-time data cards, sparkline charts, and a news ticker with actual headlines about each stock.' },
  { id: 'crypto-pulse', label: '💎 Crypto Pulse Monitor', icon: CpuIcon, category: 'Research + Build', prompt: 'Research the top 8 cryptocurrencies with their current prices, 24h change, and market cap, then build a neon-themed cyberpunk crypto monitoring dashboard with live price cards, mini charts, and a fear/greed indicator. Use actual data from the research — no fake numbers.' },
  { id: 'ai-trends', label: '🤖 AI Trends Report', icon: BrainIcon, category: 'Research + Build', prompt: 'Do deep research on the latest AI industry news from this week — new model releases, startup funding, regulatory developments, breakthrough papers — then build a professional tech publication-style webpage presenting the findings as a curated AI trends report with sections, pull quotes, and data visualizations.' },
  { id: 'movie-tonight', label: '🎬 Movie Night Picker', icon: PlayIcon, category: 'Research + Build', prompt: 'Research the top 10 movies currently in theaters or trending on streaming platforms with their ratings, genres, and brief synopses, then build a sleek movie browsing app with poster cards, rating badges, and genre filters. Dark cinema-themed design with bold typography.' },
  { id: 'music-charts', label: '🎵 Music Charts Dashboard', icon: Music2Icon, category: 'Research + Build', prompt: 'Research the current top 10 songs on the global charts with artist names, album info, and streaming numbers, then build a music streaming-style dashboard with album art placeholders, play buttons, chart position indicators, and a "Now Playing" bar. Use a dark Spotify-inspired design with vibrant accent colors.' },
  { id: 'fitness-plan', label: '💪 Personalized Fitness Hub', icon: HeartIcon, category: 'Research + Build', prompt: 'Research the latest evidence-based fitness trends, popular workout routines, and nutrition tips for 2025, then build a vibrant fitness tracking app interface with workout cards, a weekly planner, progress rings, and motivational quotes. Use energetic gradients and bold sans-serif typography.' },
  { id: 'travel-guide', label: '✈️ Instant Travel Guide', icon: GlobeIcon, category: 'Research + Build', prompt: 'Research the top 5 travel destinations trending right now with flight price ranges, best time to visit, and must-see attractions, then generate 2 AI images of stunning travel landscapes, then build a luxury travel guide website with destination cards, pricing info, and the AI-generated hero imagery.' },
  { id: 'crypto-video-dashboard', label: '💎 Crypto Dashboard + Video', icon: CpuIcon, category: 'Research + Build', prompt: 'Research the top 8 cryptocurrencies with their current prices, 24h change, and market cap, then generate an AI video of abstract blockchain data streams flowing through a dark digital void with cyan and purple particle effects as a seamless loop, then build a neon-themed cyberpunk crypto monitoring dashboard with the video as hero background and real price data displayed in glassmorphic cards with mini charts.' },
  { id: 'fitness-video-tracker', label: '💪 Fitness Hub + Video Hero', icon: HeartIcon, category: 'Research + Build', prompt: 'Research the latest evidence-based fitness trends and popular workout routines for 2025, then generate an AI video of an energetic abstract fitness scene with dynamic motion blur and warm gradient lighting as a seamless loop, then build a vibrant fitness tracking app interface with the video as the hero section background, workout cards populated with real trend data, a weekly planner, and progress rings.' },
  // ── Research + Image ──
  { id: 'weather-art', label: '🌤️ Weather Art Gallery', icon: SunIcon, category: 'Research + Image', prompt: 'Research the current weather conditions in 6 major cities around the world (Tokyo, Paris, New York, Sydney, Cairo, Rio de Janeiro), then generate 3 AI images — each depicting a surreal artistic interpretation of today\'s weather in a different city, then build a beautiful gallery webpage showcasing the weather art with real temperature data overlaid.' },
  { id: 'space-briefing', label: '🚀 Space Mission Briefing', icon: GlobeIcon, category: 'Research + Image', prompt: 'Research the latest space news — NASA missions, SpaceX launches, astronomical discoveries from this week — then generate an AI image of a dramatic deep space scene, then build a futuristic space mission briefing dashboard with dark mode, holographic-style UI elements, and real mission data from the research.' },
  { id: 'recipe-explorer', label: '🍳 AI Recipe Explorer', icon: BookOpenIcon, category: 'Research + Image', prompt: 'Research the top 5 trending recipes on the internet right now, then build a gorgeous recipe card grid website with each recipe having real ingredients, instructions, and estimated cook times. Use warm earthy tones, large food photography placeholders, and a magazine-style editorial layout.' },
  // ── Video Scenes ──
  { id: 'cinematic-hero', label: '🎬 Cinematic Hero Landing', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of a smooth cinematic aerial flyover of a futuristic neon-lit city at night with rain reflections, then build a premium SaaS landing page using that video as a full-bleed hero background. Include glassmorphic cards, bold headline typography, and a gradient CTA button floating over the video.' },
  { id: 'ocean-meditation', label: '🌊 Ocean Meditation App', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of gentle ocean waves crashing on a pristine beach at golden hour with smooth seamless loop, then build a meditation and wellness app interface using that video as the hero background. Include a breathing exercise timer, session cards, calming color palette, and soft rounded UI elements.' },
  { id: 'aurora-dashboard', label: '🌌 Aurora Data Dashboard', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of swirling aurora borealis over a frozen arctic landscape with subtle motion seamless loop, then build a professional analytics dashboard with that video as a hero section background. Include KPI metric cards, trend line charts, a dark mode sidebar, and data-dense tables with the aurora video creating atmosphere behind the header.' },
  { id: 'forest-portfolio', label: '🌿 Enchanted Forest Portfolio', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of sunlight filtering through a dense enchanted forest canopy with floating particles and gentle motion, then build a creative portfolio website with that video as the hero section. Include project showcase cards, a skills section, about me with a circular avatar, and contact form. Earthy tones with gold accents.' },
  { id: 'abstract-saas', label: '✨ Abstract Flow SaaS', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of abstract flowing liquid metallic shapes morphing smoothly in deep violet and cyan tones with seamless loop, then build a modern SaaS product page with that video behind the hero section. Include feature cards with icons, pricing tiers, testimonial carousel, and a bold gradient header.' },
  { id: 'underwater-gallery', label: '🐠 Underwater Art Gallery', icon: VideoIcon, category: 'Video Scenes', prompt: 'Generate an AI video of a dreamlike underwater scene with bioluminescent jellyfish drifting slowly through deep blue water with seamless loop, then build an art gallery website with that video as the full-page background. Include floating glass-effect cards for artwork, a masonry grid gallery, and ethereal typography.' },
  // ── Multi-Asset ──
  { id: 'brand-kit', label: '🎨 Instant Brand Kit', icon: PaletteIcon, category: 'Multi-Asset', prompt: 'Generate 4 AI images: a hero background, a product mockup, a team photo placeholder, and an abstract pattern — then build a complete brand landing page using all 4 images placed in their appropriate sections. Include navigation, hero with CTA, features grid, team section, and footer.' },
  { id: 'product-launch', label: '🚀 Product Launch Page', icon: TargetIcon, category: 'Multi-Asset', prompt: 'Generate an AI video of a sleek product rotating on a dark pedestal with dramatic lighting and seamless loop, then generate 3 AI images of the product from different angles, then build a premium product launch page with the video as hero background and the images in a features showcase section.' },
  { id: 'event-promo', label: '🎉 Event Promo Site', icon: BellIcon, category: 'Multi-Asset', prompt: 'Research the latest trends in event design and conferences, generate an AI video of an energetic crowd at a concert with colorful stage lighting seamless loop, generate 2 AI images of speaker portraits, then build an event promotional website with video hero, speaker cards, schedule timeline, ticket tiers, and venue map section.' },
  { id: 'full-brand-video', label: '🎬 Full Brand Kit + Video', icon: VideoIcon, category: 'Multi-Asset', prompt: 'Generate an AI video of a sleek product rotating on a dark pedestal with dramatic lighting and seamless loop, then generate 4 AI images: a hero background, a product mockup, a team photo placeholder, and an abstract brand pattern — then build a complete premium brand landing page using the video as the hero background and all 4 images placed in their appropriate sections including navigation, features grid, team section, and footer.' },
  { id: 'event-video-promo', label: '🎉 Event Site + Video + Images', icon: BellIcon, category: 'Multi-Asset', prompt: 'Research the latest trends in event design and tech conferences, generate an AI video of an energetic crowd at a concert with colorful stage lighting seamless loop, generate 3 AI images of professional speaker portraits, then build an event promotional website with the video hero, speaker cards using the generated images, a schedule timeline populated with realistic session data, ticket tiers, and venue info section.' },
  // ── Research + Video + Build ──
  { id: 'news-video-hero', label: '📺 News Video Dashboard', icon: VideoIcon, category: 'Research + Video + Build', prompt: 'Research the latest global news headlines from today, then generate an AI video of a dramatic newsroom environment with scrolling tickers and screen overlays as a seamless loop, then build a professional news dashboard using the video as a full-bleed hero background with real headlines from the research overlaid on glassmorphic cards.' },
  { id: 'stock-video-terminal', label: '📊 Live Stock Terminal + Video', icon: ActivityIcon, category: 'Research + Video + Build', prompt: 'Research the top 10 trending stocks today with their prices and percentage changes, then generate an AI video of abstract financial data flowing through a dark digital void with green and red particle streams as a seamless loop, then build a professional dark-mode stock trading terminal with the video as the hero background and real stock data from the research displayed in cards and sparkline charts.' },
  { id: 'space-video-briefing', label: '🚀 Space Briefing + Video', icon: GlobeIcon, category: 'Research + Video + Build', prompt: 'Research the latest space news — NASA missions, SpaceX launches, astronomical discoveries from this week — then generate an AI video of a cinematic deep space nebula flythrough with stars and cosmic dust as a seamless loop, then build a futuristic space mission briefing dashboard with the video as the full-page background and real mission data from the research displayed in holographic-style UI elements.' },
  { id: 'ai-trends-video', label: '🤖 AI Trends + Video Report', icon: BrainIcon, category: 'Research + Video + Build', prompt: 'Do deep research on the latest AI industry news from this week — new model releases, startup funding, regulatory developments — then generate an AI video of abstract neural network connections pulsing with light against a dark background as a seamless loop, then build a tech publication-style page with the video as the hero section background and the research findings presented as a curated trends report with sections, data visualizations, and source citations.' },
  { id: 'weather-video-app', label: '🌤️ Weather App + Video Sky', icon: GlobeIcon, category: 'Research + Video + Build', prompt: 'Research the current weather conditions in 5 major cities around the world (Tokyo, Paris, New York, Sydney, London), then generate an AI video of a beautiful time-lapse sky with clouds drifting and sun rays breaking through as a seamless loop, then build a premium weather dashboard app with the video as the main background and real temperature data from the research displayed in clean floating cards with weather icons.' },
  // ── Creative ──
  { id: 'retro-arcade', label: '🕹️ Retro Arcade Cabinet', icon: Gamepad2Icon, category: 'Creative', prompt: 'Build an interactive retro arcade game cabinet interface with pixel art styling, neon glow effects, a game selection grid, high score leaderboard, and animated coin-insert prompt. Use a CRT scanline overlay effect and 80s arcade color palette with hot pink and electric cyan.' },
  { id: 'magazine-editorial', label: '📖 Digital Magazine Spread', icon: BookOpenIcon, category: 'Creative', prompt: 'Research the top 3 breaking stories in technology today, then build a stunning digital magazine editorial layout with multi-column text, pull quotes, large editorial photography placeholders, drop caps, serif typography, and a sophisticated black-and-white color scheme with one accent color.' },
  { id: 'virtual-museum', label: '🏛️ Virtual Art Museum', icon: EyeIcon, category: 'Creative', prompt: 'Generate 5 AI images of different abstract artworks in various styles (impressionist, cubist, surrealist, minimalist, pop art), then build a virtual museum gallery with room-like sections, each artwork displayed on a wall with a description card, ambient lighting effects, and elegant navigation between rooms.' },
  { id: 'immersive-portfolio-video', label: '🎬 Immersive Video Portfolio', icon: VideoIcon, category: 'Creative', prompt: 'Generate an AI video of smooth cinematic abstract liquid metallic shapes morphing in deep violet and gold tones as a seamless loop, then generate 3 AI images of stunning creative project thumbnails in different styles, then build a creative portfolio website with the video as the full-page hero background, the images in a masonry gallery, and elegant navigation with scroll-triggered animations.' },
  { id: 'music-video-player', label: '🎵 Music Player + Visualizer Video', icon: Music2Icon, category: 'Creative', prompt: 'Generate an AI video of abstract audio waveforms and particle equalizer bars pulsing rhythmically in neon colors against a dark background as a seamless loop, then build a dark-themed music streaming interface with the video as the now-playing background, album art grid, playlist sidebar, and a sleek playback bar with progress indicator.' },
];
